### ISSUE TITLE
Requête d'une chaîne contenant une apostrophe

### ISSUE THREAD

**Issue by jdenisgiguere** [sigrennesmetropole/api_rva#2]
**Situation actuelle**
Lorsque je cherche « Rue d'Irlande », je ne reçois aucun retour du serveur dès que la chaine contient le caractère « ' ».

**Situation attendue**
La recherche se poursuit même si la chaine contient une apostrophe. Une recherche avec « Rue d' » retourne les noms de rues qui contiennent cette chaine de caractères.

**Information supplémentaire**
Je joins la réponse à la requête cmd=getlanes&query=Auvergne

[auvergne.json.txt](https://github.com/sigrennesmetropole/api_rva/files/274496/auvergne.json.txt)

**Comment by jquiltu** [comment]
Corrigé
```
<lane>
<insee>35051</insee>
<idlane>7252</idlane>
<fantoir>0264</fantoir>
<type>Rue</type>
<name>Rue d'Irlande</name>
<name2>RUE D'IRLANDE</name2>
<name3>d'Irlande</name3>
<nameindex>Irlande (Rue d')</nameindex>
<name4>Rue d'Irlande, Cesson-Sévigné</name4>
<lowerCorner>1356808.27 7222346.8249</lowerCorner>
<upperCorner>1356969.5521 7222590.6966</upperCorner>
</lane>
```
@jdenisgiguere

**Comment by jdenisgiguere** [comment]
Merci @jquiltu !

**Comment by MaelREBOUX** [comment]
La commande getlanes a été corrigé mais pas la commande *getfulladdresses*.
A corriger.

**Comment by jquiltu** [comment]
@MaelREBOUX : les méthodes _getaddresses_ & _getfulladdresses_ sont corrigées

**Comment by MaelREBOUX** [comment]
Cool ! Prochaine étape : changement documentation.
